name: API Auto Updater

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.12'
    secrets:
      GCP_ARTIFACT_PASSWORD:
        required: true
      NILO_BOT_APP_ID:
        required: true
      NILO_BOT_PRIVATE_KEY:
        required: true


jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up Python ${{ inputs.python_version }}
        run: uv python install ${{ inputs.python_version }}

      - name: Update dependencies
        run: make update
        env:
          UV_INDEX_NILO_PYPI_PASSWORD: ${{ secrets.GCP_ARTIFACT_PASSWORD }}

      - name: Remove database admin from Makefile
        run: |
          if [ -f Makefile ]; then
            sed -i 's/ --database admin//g' Makefile
          fi

      - name: Generate migrations
        run: |
          if grep -q "^migrations:" Makefile; then
            make migrations
          elif grep -q "^make_migrations:" Makefile; then
            make make_migrations
          fi

      - name: Run linter
        run: make style || true

      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.NILO_BOT_APP_ID }}
          private_key: ${{ secrets.NILO_BOT_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "build: update dependencies"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/bot-upgrade-dependencies
          base: staging
          delete-branch: true
          title: '[ENG-000] Update dependencies'
          body: |
            - Updated all dependencies
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
