name: API Auto Updater

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        type: string
        default: '3.11.x'
    secrets:
      gcp_artifact_password:
        required: true


jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{inputs.python_version}}
          cache: poetry
      - name: Install dependencies
        run: |
          poetry config repositories.nilo-pypi https://us-east1-python.pkg.dev/nilo-devops/python-nilo
          poetry config http-basic.nilo-pypi _json_key_base64 ${{ secrets.GCP_ARTIFACT_PASSWORD }}
          poetry config http-basic.nilo-pypi-dev _json_key_base64 ${{ secrets.GCP_ARTIFACT_PASSWORD }}
      - name: Update dependencies
        run: make update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "build: update dependencies"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/bot-upgrade-dependencies
          base: staging
          delete-branch: true
          title: '[ENG-000] Update dependencies'
          body: |
            - Updated all dependencies
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
